### PR TITLE
Added Rabbit , Skunk , Possum

### PR DESCRIPTION
**Pull request by TwisleOfficial**
also fixed the alligator

### CODE REVIEW

**Comment by TwisleOfficial** [comment]
should be working fine now

**Review by RexShack — COMMENTED** [review]
check your PR before submitting Config.Debug = true

**Comment by TwisleOfficial** [comment]
shoot my bad forgot about that should be fixed now. (sry I'm not used to using github lol)

**Comment by RexShack** [comment]
your code also needs work

**Pull request closed without merging**
